version: '2.0'
services:
  frontend:
    image: myfrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8081:3000
  backend:
    image: mybackend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - USER_POOL_ID=${USER_POOL_ID}
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - COGNITO_REGION=${COGNITO_REGION}